# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

jobs:
  include:
    - os: linux
      r:
        - release
        - devel
        - oldrel
        - 3.6.2
        - 3.4.2
        - 3.4.0
    - os: osx
      osx_image: xcode7.2
      r:
        - release
        - devel

env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false _R_CHECK_TESTS_NLINES_=0
